[workspace]
resolver = "2"

members = [
    "cli",
    "halo2",
    "halo2_gadgets",
    "halo2_proofs",
    "halo2curves",
    "poseidon",
    "entry_builder",
    "circuits",
    "runtime",
]

[workspace.dependencies]
rand = "0.8"
primitive-types = "0.12"
lazy_static = "1.4"
