[package]
name = "entry_builder"
version = "0.1.0"
edition = "2021"

[dependencies]
runtime = { path = "../runtime" }
byteorder = { version = "1.5.0", default-features = false }
hashbrown = "0.12.0"

[dev-dependencies]
serde_json = "1.0.66"

[features]
super = []
