[package]
name = "circuits"
version = "0.1.0"
edition = "2021"

[dependencies]
halo2_proofs = { path = "../halo2_proofs" }
entry_builder = { path = "../entry_builder" }
runtime = { path = "../runtime" }

[features]
super = []
